Repository frictionlessdata/frictionless-py, pull requests merged in 2024-01, with the labels that each got.

#1588 additional tests with ods file containing more than one sheet
  data/table-with-two-sheets.ods
  tests/formats/ods/test_adapter.py
  tests/formats/ods/test_parser.py
Labels: general

#1590 added support for xz and bzip2 compression
  data/table.csv.bz2
  data/table.csv.xz
  frictionless/platform.py
  frictionless/settings.py
  frictionless/system/loader.py
  tests/resources/table/test_compression.py
Labels: feature

#1620 Fix 1611 incorrect errors when validating data with a missiing required column
  frictionless/resources/table.py
  tests/validator/resource/test_schema.py
Labels: work-in-progress
